name: PyLint Runner

on: [push]
jobs:
  autoyapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: autoyapf
        id: autoyapf
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --style pep8 --recursive --in-place .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'samaravazquezperez'
          git config --global user.email 'samaravazquezperez@ada-mode.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit --allow-empty -am "Automated autoyapf fixes"
  
  build:
    needs: autoyapf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Unit testing
      id: test
      run: echo "All tests passed"

    - name: Run Pylint
      id: lint
      run: |
        python linting.py --path application.py --threshold 6
    - name: Check status
        if: steps.lint.outcome != 'success' || steps.test.outcome != 'success'
        run: |
          git reset HEAD^ --hard
          git push origin -f
    - name: Check status
        if: success()
        run: |
          git push